---
title: "Superfast PRS"
author: "Julian Echave"
date: "5/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```


```{r}
# Load libraries and functions
library(here)
library(bio3d)
library(tidyverse)
library(cowplot)
library(penm)
library(jefuns)

library(patchwork)
```

```{r}
# Set parameters
pdb_id = "2acy_A"
# set wt
pdb <- read.pdb(here("data-raw/2acy_A.pdb"))
wt <- set_enm(pdb,  "ca",  "ming_wall",  10.5,  F)
mut <- get_mutant_site(wt, 80, 1)
```

```{r}
dat <- calculate_dvsj_mut(wt, 10, "lfenm", 0.3, 1)
```



# Superfast matrices

```{r, eval = F}
# profiling
library(profvis)



profvis(prs(wt, 2, "lfenm", 0.3, 2))


mutants <-  get_mutants_table(wt, 10, "lfenm", 0.3, 2)
profvis(calculate_dfij(mutants))
profvis(calculate_dfnj(mutants))

profvis(calculate_dfj(mutants, beta))
```

```{r}
library(microbenchmark)
microbenchmark(calculate_dfij(mutants), calculate_dfnj(mutants),
               calculate_dfij.fast(wt), times = 1)



```

```{r}
kmat_sqrt <- get_kmat_sqrt(wt)
microbenchmark(calculate_de2i(wt, mut, kmat_sqrt),
               calculate_de2n(wt, mut),
               calculate_dr2i(wt, mut),
               calculate_dr2n(wt, mut),
               calculate_df2i(wt, mut),
               calculate_df2n(wt, mut),
               times = 10)
```
```{r}
microbenchmark(calculate_dfnj(mutants_10),
               calculate_dfnj.fast(wt),
               calculate_dfij(mutants_10),
               calculate_dfij.fast(wt),
               times = 1)

```

```{r}
library(microbenchmark)

kmat <- get_kmat(wt)
cmat <- get_cmat(wt)
dr <- get_xyz(mut) - get_xyz(wt)
f <- kmat %*% dr
f10 <- cbind(f, f, f, f, f, f, f, f, f, f)
f20 <- cbind(f10, f10, f10, f10, f10, f10)

loop10 <- function(cmat, f10) {
  smat <- matrix(NA, nrow(kmat), ncol(f10))
  for (j in seq(ncol(f10))) {
    smat[,j] <- kmat %*% f10[,j]
  }
  smat
}

nzf <- !near(f, 0)


library(Matrix)
cmat.matrix <- Matrix(cmat)
f20.matrix <- Matrix(f20, sparse = T)

microbenchmark(cmat %*% f20,  
               cmat[,nzf] %*% f20[nzf, ], loop10(cmat, f20), 
               cmat.matrix %*% f20.matrix, times = 10)

```
```{r}
microbenchmark(prs.new(wt, 50, "lfenm", 0.3, 2, 1024), prs.old(wt, 50, "lfenm", 0.3, 2), prs.fast(wt, 0.3, 2), times = 1)


microbenchmark(prs.new(wt, 50, "lfenm", 0.3, 2, 1024),  calculate_dfij.fast(wt, 0.3, 2), times = 1)
```


```{r}
dat.new <- prs.new(wt, 50, "lfenm", 0.3, 2, 1024) %>% 
  select(i, j, df2ij, de2ij, dr2ij) %>% 
  pivot_longer(cols = df2ij:dr2ij,
               names_to = "response_type",
               values_to = "value")

dat.fast <- calculate_dfij.fast(wt, 0.3, 2) %>% 
  select(i, j, df2ij, de2ij, dr2ij) %>% 
  pivot_longer(cols = df2ij:dr2ij,
               names_to = "response_type",
               values_to = "value")

dat <- inner_join(dat.new, dat.fast, by = c("i", "j", "response_type"), suffix = c(".prs", ".fast"))

dat %>% 
  ggplot(aes(value.fast, value.prs)) +
  geom_point() +
  geom_abline() +
  facet_wrap(~response_type, ncol = 3, scales = "free")


```

