---
title: "Superfast PRS"
author: "Julian Echave"
date: "5/12/2020"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```


```{r}
# Load libraries and functions
library(here)
library(bio3d)
library(tidyverse)
library(cowplot)
library(penm)
library(jefuns)

library(patchwork)
```

```{r}
# Set parameters
pdb_id = "2acy_A"
```


# Superfast matrices

# cpu time

## comparison of cpu times

```{r}
library(microbenchmark)
# set wt
pdb <- read.pdb(here("data-raw/2acy_A.pdb"))
wt <- set_enm(pdb,  "ca",  "ming_wall",  10.5,  F)

prs_slow <- function(wt, nmut_per_site = 10) {
  mutants <- get_mutants_table(wt, nmut_per_site, mut_model = "lfenm", mut_dl_sigma = 0.3, mut_sd_min = 2)
  calculate_dfnj(mutants)
}



prs_fast <- function(wt) {
  fast_calculate_dfnj(wt)
}

get_mutants <- function(wt, nmut_per_site) get_mutants_table(wt, nmut_per_site, "lfenm", 0.3, 2)

mutants_1 <- get_mutants_table(wt, 1, "lfenm", 0.3, 2)
mutants_5 <- get_mutants_table(wt, 5, "lfenm", 0.3, 2)
mutants_10 <- get_mutants_table(wt, 10, "lfenm", 0.3, 2)



# mb <- microbenchmark(prs_slow(wt, 1), prs_slow(wt, 5), prs_slow(wt, 10),  prs_fast(wt),  times = 1)

mb <- microbenchmark(get_mutants(wt, 1), calculate_dfnj(mutants_1),
                     get_mutants(wt, 5), calculate_dfnj(mutants_5),
                     get_mutants(wt, 10), calculate_dfnj(mutants_10),
                     fast_calculate_dfnj(wt),
                     times = 1)

mb %>% 
  ggplot(aes(expr, time / 10^6)) +
  geom_col() +
  ylab("cpu time (ms)") +
  xlab("function call") +
  geom_label(aes(label = round(time / 10^6, 0))) +
  coord_flip()

  
```


# Convergence

## Convergence of prs_slow towards prs_fast

```{r}
# set wt
pdb <- read.pdb(here("data-raw/2acy_A.pdb"))
wt <- set_enm(pdb, "ca", "ming_wall", 10.5, F)

# Slow prs calculation (simulation)
mutants <- get_mutants_table(wt, nmut_per_site = 50, mut_model = "lfenm", mut_dl_sigma = 0.3, mut_sd_min = 2)
dfnj_slow <- calculate_dfnj(mutants)

# Fast prs calculation (analytical)
dfnj_fast <- fast_calculate_dfnj(wt) %>% 
  rename(dr2nj_fast = dr2nj, de2nj_fast = de2nj, df2nj_fast = df2nj) 
```

```{r}
dfnj_mean <- dfnj_slow %>% 
  filter(mutation > 0) %>% 
  mutate(n = mode) %>% 
  select(n, j, mutation, everything()) %>% 
  arrange(n, j, mutation) %>% 
  group_by(n, j) %>% 
  mutate(dr2nj_mean = cumsum(dr2nj) / mutation,
         de2nj_mean = cumsum(de2nj) / mutation,
         df2nj_mean = cumsum(df2nj) / mutation)   %>% 
  select(-dr2nj, -de2nj, -df2nj)  


dfnj_all <- inner_join(dfnj_mean, dfnj_fast)
```

```{r}

# matrix convergence

df_matrix <- dfnj_all %>% 
  ungroup() %>% 
  group_by(mutation) %>% 
  summarise(dr2nj_error = sd(dr2nj_mean - dr2nj_fast) / mean(dr2nj_fast),
            de2nj_error = sd(de2nj_mean - de2nj_fast) / mean(de2nj_fast),
            df2nj_error = sd(df2nj_mean - df2nj_fast) / mean(df2nj_fast)) %>% 
  pivot_longer(cols = dr2nj_error:df2nj_error,
               names_to = "error",
               values_to = "value") %>% 
  mutate(error = factor(error, levels = c("dr2nj_error", "de2nj_error", "df2nj_error"))) 



# response profile convergence

df_response <- dfnj_all %>% 
  ungroup() %>% 
  group_by(n, mutation) %>% 
  summarise(dr2nj_mean = sum(dr2nj_mean),
            dr2nj_fast = sum(dr2nj_fast),
            de2nj_mean = sum(de2nj_mean),
            de2nj_fast = sum(de2nj_fast),
            df2nj_mean = sum(df2nj_mean),
            df2nj_fast = sum(df2nj_fast)) %>% 
  ungroup() %>% 
  arrange(n, mutation) %>% 
  group_by(mutation) %>% 
  summarise(dr2nj_error = sd(dr2nj_mean - dr2nj_fast) / mean(dr2nj_fast),
            de2nj_error = sd(de2nj_mean - de2nj_fast) / mean(de2nj_fast),
            df2nj_error = sd(df2nj_mean - df2nj_fast) / mean(df2nj_fast)) %>% 
  pivot_longer(cols = dr2nj_error:df2nj_error,
               names_to = "error",
               values_to = "value") %>% 
  mutate(error = factor(error, levels = c("dr2nj_error", "de2nj_error", "df2nj_error"))) 

# influence profile convergence

df_influence <- dfnj_all %>% 
  ungroup() %>% 
  group_by(j, mutation) %>% 
  summarise(dr2nj_mean = sum(dr2nj_mean),
            dr2nj_fast = sum(dr2nj_fast),
            de2nj_mean = sum(de2nj_mean),
            de2nj_fast = sum(de2nj_fast),
            df2nj_mean = sum(df2nj_mean),
            df2nj_fast = sum(df2nj_fast)) %>% 
  ungroup() %>% 
  arrange(j, mutation) %>% 
  group_by(mutation) %>% 
  summarise(dr2nj_error = sd(dr2nj_mean - dr2nj_fast) / mean(dr2nj_fast),
            de2nj_error = sd(de2nj_mean - de2nj_fast) / mean(de2nj_fast),
            df2nj_error = sd(df2nj_mean - df2nj_fast) / mean(df2nj_fast)) %>% 
  pivot_longer(cols = dr2nj_error:df2nj_error,
               names_to = "error",
               values_to = "value") %>% 
  mutate(error = factor(error, levels = c("dr2nj_error", "de2nj_error", "df2nj_error")))
```


```{r}
df_matrix$type <- "Rnj"
df_response$type <- "response"
df_influence$type  <- "influence"

df <- df_matrix %>% 
  rbind(df_response) %>% 
  rbind(df_influence)

df %>% 
  ggplot(aes(mutation, value, color = type)) +
  geom_line() +
  facet_grid(. ~ error) +
  ylab("relative error") +
  xlab("number of mutant scans") +
  scale_y_log10() +
  theme_minimal()

```




