---
title: "Superfast PRS, energy response"
author: "Julian Echave"
date: "5/12/2020"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```


```{r}
# Load libraries and functions
library(here)
library(bio3d)
library(tidyverse)
library(cowplot)
library(penm)
library(jefuns)

library(patchwork)
```

```{r}
# Set parameters
pdb_id = "2acy_A"
```



## comparison of cpu times

```{r}
library(microbenchmark)
# set wt
pdb <- read.pdb(here("data-raw/2acy_A.pdb"))
wt <- set_enm(pdb,  "ca",  "ming_wall",  10.5,  F)


get_mutants <- function(wt, nmut_per_site) get_mutants_table(wt, nmut_per_site, "lfenm", 0.3, 2)

mutants_1 <- get_mutants_table(wt, 1, "lfenm", 0.3, 2)
mutants_5 <- get_mutants_table(wt, 5, "lfenm", 0.3, 2)
mutants_10 <- get_mutants_table(wt, 10, "lfenm", 0.3, 2)



# mb <- microbenchmark(prs_slow(wt, 1), prs_slow(wt, 5), prs_slow(wt, 10),  prs_fast(wt),  times = 1)

mb <- microbenchmark(get_mutants(wt, 1), delta_energy(mutants_1, beta_boltzmann()),
                     get_mutants(wt, 5), delta_energy(mutants_5, beta_boltzmann()),
                     get_mutants(wt, 10), delta_energy(mutants_10, beta_boltzmann()),
                     fast_delta_energy(wt, 0.3, 2),
                     times = 1) %>% 
  mutate(expr = factor(expr, labels = c("slow.scan_1", "slow.de_1", "slow.scan_5", "slow.de_5", "slow.scan_10", "slow.de_10", "fast.de")))




p1 <- mb %>% 
  ggplot(aes(expr, time / 10^6)) +
  geom_col() +
  ylab("cpu time (ms)") +
  xlab("function call") +
  geom_label(aes(label = round(time / 10^6, 0))) +
  coord_flip() +
  ggtitle("influence profiles")



mb <- microbenchmark(get_mutants(wt, 1), delta_energy_site(mutants_1),
                     get_mutants(wt, 5), delta_energy_site(mutants_5),
                     get_mutants(wt, 10), delta_energy_site(mutants_10),
                     fast_delta_energy_site(wt, 0.3, 2),
                     times = 1) %>% 
  mutate(expr = factor(expr, labels = c("slow.scan_1", "slow.de_1", "slow.scan_5", "slow.de_5", "slow.scan_10", "slow.de_10", "fast.de")))



p2 <- mb %>% 
  ggplot(aes(expr, time / 10^6)) +
  geom_col() +
  ylab("cpu time (ms)") +
  xlab("function call") +
  geom_label(aes(label = round(time / 10^6, 0))) +
  coord_flip() +
  ggtitle("response matrix")


p1 + p2

  
```

## Comparison of results

```{r}
mut_dl_sigma <- 0.3

# set wt
pdb <- read.pdb(here("data-raw/2acy_A.pdb"))
wt <- set_enm(pdb, "ca", "ming_wall", 10.5, F)

# fast response matrices and profiles
deij_fast <- fast_delta_energy_site(wt, mut_dl_sigma, 2)
dej_fast <- fast_delta_energy(wt, mut_dl_sigma, 2)


# slow response matrices and profiles
mutants <- get_mutants_table(wt, 30, "lfenm", mut_dl_sigma, 2)
deij_slow <- delta_energy_site(mutants)
dej_slow <- delta_energy(mutants, beta_boltzmann())
```



# Convergence

## Convergence of prs_slow towards prs_fast

```{r}

# response matrix

deij_slow_long <- deij_slow %>% 
  pivot_longer(cols = de2ij:dvmij,
               names_to = "response",
               values_to = "value")

deij_fast_long <- deij_fast %>% 
  pivot_longer(cols = de2ij:dvmij,
               names_to = "response",
               values_to = "value")


deij <- inner_join(deij_slow_long, deij_fast_long, by = c("i", "j", "response"), suffix = c(".slow", ".fast"))

deij_mean <- deij %>% 
  filter(mutation > 0) %>% 
  select(i, j, mutation, everything()) %>% 
  arrange(response, i, j, value.fast, mutation) %>% 
  group_by(response, i, j, value.fast) %>% 
  mutate(value.slow.mean = cumsum(value.slow) / mutation)  %>% 
  select(-value.slow) %>% 
  rename(value.slow = value.slow.mean)

deij_mean %>% 
  # filter(abs(j-i) == 1) %>% 
  filter(mutation %in% c(10, 20, 30)) %>% 
  ggplot(aes(value.fast, value.slow)) +
  geom_point(size = .5, alpha = .5) +
  geom_abline() +
  geom_smooth() +
  facet_wrap(~mutation+response, ncol = 3, scales = "free")
```




## influence profiles

```{r}
# influence profiles
  
dej_mean <- deij_mean %>% 
  group_by(response, mutation, j) %>% 
  summarise(value.slow = 1/2 * sum(value.slow), value.fast = 1/2 * sum(value.fast))

dej_mean %>% 
filter(mutation %in% c(10, 20, 30)) %>% 
  ggplot(aes(value.fast, value.slow)) +
  geom_point(size = .5, alpha = .5) +
  geom_abline() +
  geom_smooth() +
  facet_grid(mutation~response, scales = "free") +
  ggtitle("influence profiles")
```

## response profiles

```{r}

dei_mean <- deij_mean %>% 
  group_by(response, mutation, i) %>% 
  summarise(value.slow = mean(value.slow), value.fast =  mean(value.fast))

dei_mean %>% 
filter(mutation %in% c(10, 20, 30)) %>% 
  ggplot(aes(value.fast, value.slow)) +
  geom_point(size = .5, alpha = .5) +
  geom_abline() +
  geom_smooth() +
  facet_grid(mutation~response, scales = "free") +
  ggtitle("influence profiles")
```


```{r}
deij_mean %>% 
  mutate(residual = value.slow - value.fast) %>% 
  group_by(response, mutation) %>% 
  summarise(error = sd(residual)/mean(value.fast)) %>%
  ggplot(aes(mutation, error, color = response)) +
  geom_line()

```


