---
title: "penm development log"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## 30 April 2020

### Eliminate need to use  `ideal` in enm and lfenm calculations

`ideal` is the ideal protein structure, needed to calculate `v_stress`, `dv_activation`, and `g_entropy_activation`.
To eliminate it, I can just avoid calling these functions to set up and mutate `wt`

1. Moved  `v_stress`, `dv_activation`, and `g_entropy_activation` to *activation.R*
2. Split old enm_energy into two functions: enm_energy_activation (it calls dv_activation and g_entropy_activation) and enm_energy that calculates just v_min and g_entropy


### Eliminate active-site dependent info from enm and lfenm calculations

pdb_active_site indices are used to calculate cmat_activation, kmat_activation, and activation energies. I do not need this in the prot object. If needed, I can add it later. 

1. I moved everything related to active site into file activation.R (need to test it, current tests don't use it).
2. Everything else is independent of either "pdb_site_active" or "ideal". Therefore, it should run for tasks that do not depend on defining active sites.
3. Modified tests accordingly (eliminating dummy active site and ideal).
4. Commited changes to git and github

### Make a one-button setup of prot object and test


right now setting up the protein object is done by first reading a pdb file into a bio3d pdb object, then calling prot_sc or prot_ca to initialize the prot object, then calling init_prot to cmplete it. Join prot_sc/prot_ca with init_prot into a single function `set_prot(pdb)` 
Consider adding the enm parameters to prot to be used when passing to other functions(prot)

- Replaced previous "pdb_sc" followed by "init_prot" by a single set_prot(pdb,...) function that sets up the enm, performs nma etc. 
- Added enm_param to prot object
- Set up a prot_test.R test in tests/testthat directory, which is run when devtools::test()
- Added objects pdb_2acy_A and prot_2acy_A to data folder for testing
Tested and commited all changes.

## 1  May  2020

Refactor enm

### beta and energy terms

beta = 1/(k_boltzman T), depends on temperature. Therefore it is not a property of the protein but, rather, something that depends on the protein's properties and the environment's temperature. For this reason, it would be better to calculate energies when needed, rather than attaching energy terms to the prot object.

Thus, eliminate energy from protein object (and change everything accordingly)

- deleted enm_energy and enm_energy_activation functions
- deleted all calls to enm_energy and recursively...
- deleted query functions get_v_min, get_g_entropy, get_v_min_activaiton, get_g_entropy_activation, get_v_stress
- tested
- commited to git and github



### make plot_enm functions good enough to move to package

- added some more plots to test_enm.Rmd
- fixed an issue: graph setting (in set_enm_xyz) missed some i-(i+1) contacts for which dij > d_max (not a problem for CA models, but it's a problem for SC models). 
- Changed kij_anm and kij_ming_wall so that they don't set these i-(i+1) kij to 0.
- Tested and commited.


## 2 May 2020

### Deleted `add_site_indexes()`

- added `nsites` and `site` to the result returned by `prot_sc()` and `prot_ca()` 
- tested and commited

### Deleted `add_enm()`

- renamed `enm_set_xyz` to `enm_from_xyz`
- made `enm_from_xyz` call `nma(kmat)` and return also `mode, evalue, umat, cmat`
- made set_prot call `enm_from_xyz` directly, rather than `add_enm`
- deleted `add_enm`
- tested and commited


### Moved non-binary data to `./data_raw`



## 3 May 2020

### merged set_prot.R and add_prot.R into single file 












