---
title: "Test enm functions"
author: "Julian Echave"
date: "4/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Load libraries and functions

```{r}
# load libraries
library(tidyverse)
library(ggridges)
library(cowplot)
library(bio3d)
library(penm)
library(jefuns)


# source functions
source("plot_enm.R")
```


# Read and perform ENM NMA of wild-type protein


## Set up Elastic Network Model

```{r}
## read pdb filec
pdb_file <- "data-raw/2acy_A.pdb"
pdb <- read.pdb(pdb_file)

# set up the protein's enm
prot <- set_prot(pdb, node = "ca", model = "ming_wall", d_max = 10.5, frustrated = FALSE)
                
str(prot)
```



### Calculate prot energy

```{r}
tibble(v_min = enm_v_min(prot), 
       g_entropy = enm_g_entropy(prot, beta_boltzmann(T = 298)))
```


## Plot and compare msf


```{r}
plot_msf_site(prot, d_max = prot$enm_param$d_max)
```

## Plot normal-mode matrix

```{r}
plot_umat2(prot)
```

## Plot a few normal modes
  
```{r}
nmodes <- max(prot$enm$mode)
plot_modes(prot, plot_modes = c(1, 2, 3, 4, nmodes - 3, nmodes - 2, nmodes - 1, nmodes))
```
33 Plot eigenvalues


```{r}
plot_eigenvalue_vs_mode <- function(prot) {
   df <-  tibble(mode = prot$enm$mode, eigenvalue = prot$enm$evalue, msf = 1 / eigenvalue) 
   
   p <- df  %>% 
     ggplot(aes(mode, eigenvalue)) +
     geom_point() +
     theme_cowplot() 
   
   p
     
}

plot_eigenvalue_spectrum <- function(prot) {
   df <-  tibble(mode = prot$enm$mode, eigenvalue = prot$enm$evalue) 
   
   p <- df  %>% 
     ggplot(aes(eigenvalue)) +
     geom_histogram() +
     theme_cowplot() 
   
   p
     
}

plot_msf_vs_mode <- function(prot) {
   df <-  tibble(mode = prot$enm$mode, msf = 1 / prot$enm$evalue) 
   
   p <- df  %>% 
     ggplot(aes(mode, msf)) +
     geom_point() +
     theme_cowplot() 
   
   p
     
}

plot_msf_mode_spectrum <- function(prot) {
   df <-  tibble(mode = prot$enm$mode, msf = 1 / prot$enm$evalue) 
   
   p <- df  %>% 
     ggplot(aes(msf)) +
     geom_histogram() +
     theme_cowplot() 
   
   p
     
}


plot_grid(plot_eigenvalue_vs_mode(prot),
          plot_eigenvalue_spectrum(prot),
          plot_msf_vs_mode(prot),
          plot_msf_mode_spectrum(prot))








```

