# Refresh data to use in test_penm.R

## ----------------------------------------------------------------------------------------------------------------------
# load libraries
# Load penm from SOURCE, not the installed package: fixtures must be
# generated by the code as it is now, not by whatever was last installed.
devtools::load_all()
library(testthat)  # for test_path()


## ----------------------------------------------------------------------------------------------------------------------
load(test_path("fixtures", "pdb_2acy_A.rda"))

wt <- set_enm(pdb_2acy_A, node = "ca", model = "ming_wall", d_max = 10.5, frustrated = FALSE)
save(wt, file = test_path("fixtures", "wt.rda"))

## ----------------------------------------------------------------------------------------------------------------------

mut_lf  <- get_mutant_site(wt, site_mut = 80, mutation = 1,
                           mut_model = "lfenm", mut_dl_sigma = 0.3, mut_sd_min = 1)

save(mut_lf, file = test_path("fixtures", "mut_lf.rda"))

## ----------------------------------------------------------------------------------------------------------------------
skip <-  TRUE
if (!skip) {
  mut_qf <- get_mutant_site(wt, site_mut = 80, mutation = 1,
                            mut_model = "sclfenm", mut_dl_sigma = 0.3, mut_sd_min = 1)
  save(mut_qf, file = test_path("fixtures", "mut_qf.rda"))
}






