## code to prepare `DATASET` dataset goes here

# usethis::use_data("DATASET")

# Load penm from SOURCE, not the installed package: fixtures must be
# generated by the code as it is now, not by whatever was last installed.
devtools::load_all()
library(testthat)  # for test_path()

load(test_path("fixtures", "pdb_2acy_A.rda"))

prot_2acy_A_ming_wall_ca <- set_enm(pdb_2acy_A, node = "ca", model = "ming_wall", d_max = 10.5, frustrated = FALSE)

save(prot_2acy_A_ming_wall_ca, file = test_path("fixtures", "prot_2acy_A_ming_wall_ca.rda"))



