---
title: "Generate perturbation response scanning data"
author: "Julian Echave"
date: "5/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = TRUE, warning = TRUE)
```


```{r}
# Load libraries and functions
library(here)
library(tidyverse)
library(bio3d)
library(penm)
library(jefuns)
```

## Set parameters

```{r}
# set parameters
pdb_id <- "2acy_A"

# enm parameters
enm_node <- "ca"
enm_model <- "ming_wall"
enm_d_max <- 10.5
enm_frustrated <- F

# mut parameters
nmut_per_site <- 10
mut_model <- "lfenm"
mut_dl_sigma <- 0.3
mut_sd_min <- 2

# file names
# input
pdb_fname <- here("data-raw", paste0(pdb_id, ".pdb"))

# output
mut_param_fname <- here("data-raw", paste0(pdb_id, "_mut_param.csv"))
dej_fname <- here("data-raw", paste0(pdb_id, "_dfej.csv"))
dfij_fname <- here("data-raw", paste0(pdb_id, "_dfij.csv"))
dfnj_fname <- here("data-raw", paste0(pdb_id, "_dfnj.csv"))
```


## Scan mutations

```{r}
# set wt
pdb <- read.pdb(here("data-raw/2acy_A.pdb"))
wt <- set_enm(pdb, enm_node, enm_model, enm_d_max, enm_frustrated)
# get mutant table
prs <- prs(wt, nmut_per_site, mut_model, mut_dl_sigma, mut_sd_min, beta = beta_boltzmann())

str(prs)
```

```{r}
write_csv(as_tibble(prs$mut_param), mut_param_fname)
write_csv(prs$dej, dej_fname)
write_csv(prs$dfij, dfij_fname)
write_csv(prs$dfnj, dfnj_fname)
```

