library(here)
source(here("R", "applications.R"))
set.seed(1)
make_prot<-function(N=40){t<-seq(0,6*pi,length.out=N)
  as.vector(rbind(4*cos(t)+rnorm(N,0,.4),4*sin(t)+rnorm(N,0,.4),1.2*t/2+rnorm(N,0,.4)))}
r0<-make_prot(40); wt<-new_state(r0, d_max=10.5)
cat("protein: N =",length(r0)/3," edges =",nrow(wt$pr),"\n\n")

set.seed(2024)
sc <- scan_sites(wt, nmut=20, sigma=0.3, model="sclfenm", verbose=FALSE)
cat("=== single-mutation scan, sclfenm, 20 mutations/site ===\n")
print(round(head(sc[order(-sc$dV),],8),4))
cat("\ncorrelations across sites:\n")
cat("  cor(dV, contact number) =", round(cor(sc$dV, sc$cn),3), "\n")
cat("  cor(dr2, contact number)=", round(cor(sc$dr2,sc$cn),3), "\n")
cat("  cor(dV, dr2)            =", round(cor(sc$dV, sc$dr2),3), "\n")
cat("  cor(dTS, contact number)=", round(cor(sc$dTS,sc$cn),3), "\n")
saveRDS(sc, here("data", "scan_sclfenm.rds"))

## same scan under lfenm, to show what differs
set.seed(2024)
sl <- scan_sites(wt, nmut=20, sigma=0.3, model="lfenm", verbose=FALSE)
cat("\n=== lfenm vs sclfenm on the same mutations ===\n")
cat("  dV  identical? ", isTRUE(all.equal(sc$dV, sl$dV)), "\n")
cat("  dr2 identical? ", isTRUE(all.equal(sc$dr2,sl$dr2)), "\n")
cat("  dTS lfenm range:", paste(round(range(sl$dTS),8),collapse=" .. "), "(zero by construction)\n")
cat("  dTS sclfenm range:", paste(round(range(sc$dTS),5),collapse=" .. "),"\n")
saveRDS(sl, here("data", "scan_lfenm.rds"))
