---
title: "Notes"
author: "Julian Echave"
date: "5/9/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Many ways of updating ENM...

### LFENM

The LFENM does not change $K$. Thus, the structure changes, but not the normal modes, or entropy: there's a shift in the center of the potential energy well without any reorientation.

### SC-LFENM

The SC-LFENM takes into account that by definition in ENM's $K$ is built from the equilibrium conformation. Therefore, if we change the structure due to, for instance, a linearly-forcing term in the hamiltonian, the network's $K$ should change accordingly. This was used in (Echave 2012) to derive the effect of mutations on normal modes.

Now, for running single-point mutation scans this is fine, but for longer evolutionary trajectories an issue arises: shall we use the updated $K$ to calculate further deformations or just when we want to calculate changes in normal modes and/or entropies?

Thus, there are two possibilties:
- Run LFENM simulation and update K only for calculating entropies and/or changes in dynamics (fast)
- Run full SC-LFENM simulation, updating K at each step and using updated K to calculate deformations (slow)

### Issues
- Rigorously, should I use $K_{wt}$ or $K_{mut}$ to calculate $\delta \mathbf{r}$?
- **reversibility:** Are mutations reversible? 
- **path-independence:** Is the result of introducing two successive mutations independent of their order? 

### Connectivity changes

A problem with any method of self-consistently changing $K$ is that in principle the network topology can change. This may result in relatively large changes in energy because of changes in the total number of contacts... 

### $V_0$ changes

Introducing a mutation adds stress to the network. Before recalculating a self-consistent relaxed network, we may want to add to the hamiltonian the $\delta V_0$ that results from the mutational stress that cannot be totally relaxed.



