#' calcualte all fast response matrices and profiles
#'
prs_matrices_and_profiles <- function(wt, nmut_per_site, mut_model, mut_dl_sigma, mut_sd_min, seed) {

  mutants <- generate_mutants(wt, nmut_per_site, mut_model, mut_dl_sigma, mut_sd_min, seed)

  enm_param <- get_enm_param(wt)
  mut_param <- lst(nmut_per_site, mut_model, mut_dl_sigma, mut_sd_min)

  dfij <- calculate_dfij.prs(mutants)

  dfj <- dfij %>%
    group_by(j, mutation) %>%
    summarise(dr2j = sum(dr2ij),
              df2j = sum(df2ij),
              de2j = 1/2 * sum(de2ij),
              dvsj = 1/2 * sum(dvsij),
              dvmj = 1/2 * sum(dvmij))

  dfi <- dfij %>%
    group_by(i, mutation) %>%
    summarise(dr2i = mean(dr2ij),
              df2i = mean(df2ij),
              de2i = mean(de2ij),
              dvsi = mean(dvsij),
              dvmi = mean(dvmij))

  dfnj <- calculate_dfnj.prs(mutants)

  dfn <- dfnj %>%
    group_by(n, mutation) %>%
    summarise(dr2n = mean(dr2nj),
              df2n = mean(df2nj),
              de2n = mean(de2nj))

  lst(enm_param, mut_param, dfi, dfj,  dfij,  dfnj, dfn)
}


#' get mutant table
#'
generate_mutants <- function(wt, nmut_per_site, mut_model, mut_dl_sigma, mut_sd_min, seed) {
  mutation <- seq(from = 0, to = nmut_per_site)
  j <- get_site(wt)
  # get mutants
  mutants <-  expand_grid(wt = list(wt), j, mutation)

  mutants <- mutants %>%
    mutate(mut = pmap(list(wt, j, mutation), get_mutant_site,
                      mut_model = mut_model, mut_dl_sigma = mut_dl_sigma, mut_sd_min = mut_sd_min, seed = seed))
  mutants
}

# Site-site response matrices ---------------------------------------------


#' Calculate site-by-site response matrices
#'
calculate_dfij.prs <- function(mutants) {
  mutants %>%
    calculate_dr2ij.prs() %>%
    inner_join(calculate_df2ij.prs(mutants)) %>%
    inner_join(calculate_de2ij.prs(mutants)) %>%
    inner_join(calculate_dvsij.prs(mutants)) %>%
    mutate(dvmij = dvsij - de2ij)
}

calculate_dr2ij.prs <- function(mutants) {
  result <- mutants %>%
    mutate(i = map(wt, get_site),
           dr2ij = map2(wt, mut, calculate_dr2i)) %>%
    select(-wt, -mut) %>%
    unnest(c(i, dr2ij)) %>%
    select(i, j, mutation, dr2ij)

  result
}

calculate_df2ij.prs <- function(mutants) {
  result <- mutants %>%
    mutate(i = map(wt, get_site),
           df2ij = map2(wt, mut, calculate_df2i)) %>%
    select(-wt, -mut) %>%
    unnest(c(i, df2ij)) %>%
    select(i, j, mutation, df2ij)

  result
}

calculate_de2ij.prs <- function(mutants) {
  # structural differences, site analysis
  wt <- mutants$wt[[1]]
  kmat_sqrt <- get_kmat_sqrt(wt)

  result <- mutants %>%
    mutate(i = map(wt, get_site),
           de2ij = map2(wt, mut, calculate_de2i, kmat_sqrt = kmat_sqrt)) %>%
    select(-wt, -mut) %>%
    unnest(c(i,  de2ij)) %>%
    select(i, j, mutation, de2ij)

  result
}

calculate_dvsij.prs <- function(mutants) {
  # structural differences, site analysis
  result <- mutants %>%
    mutate(i = map(wt, get_site),
           dvsij = map2(wt, mut, calculate_dvsi.noindel)) %>%
    select(-wt, -mut) %>%
    unnest(c(i, dvsij)) %>%
    select(i, j, mutation, dvsij)

  result
}

calculate_dvmij.prs <- function(mutants) {
  # structural differences, site analysis
  de2ij <- calculate_de2ij.prs(mutants)
  dvsij <- calculate_dvsij.prs(mutants)

  result <- inner_join(de2ij, dvsij) %>%
    mutate(dvmij = dvsij - de2ij) %>%
    select(i, j, mutation, dvmij)

  result
}



# Influence profiles ------------------------------------------------------

#' calculate influence profiles
#'
calculate_dfj.prs <- function(mutants) {
  calculate_dr2j.prs(mutants) %>%
    inner_join(calculate_df2j.prs(mutants)) %>%
    inner_join(calculate_de2j.prs(mutants)) %>%
    inner_join(calculate_dvsj.prs(mutants)) %>%
    inner_join(calculate_dvmj.prs(mutants))
}


#' calculate influence profile dr2j (structure)
#'
#' @param mutants is a set of mutants generated by generate_mutants
#'
#' @return an influence vector, where each element is the total response to a mutation at site j
#'
calculate_dr2j.prs <- function(mutants) {
  calculate_dr2ij.prs(mutants) %>%
    group_by(j, mutation) %>%
    summarise(dr2j = sum(dr2ij)) %>%
    ungroup()
}

#' calculate influence profile df2j (force)
#'
#' @inherit calculate_dr2j.prs
#'
calculate_df2j.prs <- function(mutants) {
  calculate_df2ij.prs(mutants) %>%
    group_by(j, mutation) %>%
    summarise(df2j = sum(df2ij)) %>%
    ungroup()
}


#' calculate influence profile de2j (relaxation)
#'
#' @inherit calculate_dr2j.prs
#'
calculate_de2j.prs <- function(mutants) {
  calculate_de2ij.prs(mutants) %>%
    group_by(j, mutation) %>%
    summarise(de2j = 0.5 * sum(de2ij)) %>%
    ungroup()
}

#' calculate influence profile dvsj (stress)
#'
#' @inherit calculate_dr2j.prs
#'
calculate_dvsj.prs <- function(mutants) {
  calculate_dvsij.prs(mutants) %>%
    group_by(j, mutation) %>%
    summarise(dvsj = 0.5 * sum(dvsij)) %>%
    ungroup()
}

#' calculate influence profile dvmj (minimumn energy)
#'
#' @inherit calculate_dr2j.prs
#'
calculate_dvmj.prs <- function(mutants) {
  calculate_dvmij.prs(mutants) %>%
    group_by(j, mutation) %>%
    summarise(dvmj = 0.5 * sum(dvmij)) %>%
    ungroup()
}

# Response profiles ------------------------------------------------------


calculate_dfi.prs <- function(mutants) {
  calculate_dr2i.prs(mutants) %>%
    inner_join(calculate_df2i.prs(mutants)) %>%
    inner_join(calculate_de2i.prs(mutants)) %>%
    inner_join(calculate_dvsi.prs(mutants)) %>%
    inner_join(calculate_dvmi.prs(mutants))
}


calculate_dr2i.prs <- function(mutants) {
  calculate_dr2ij.prs(mutants) %>%
    group_by(i, mutation) %>%
    summarise(dr2i = mean(dr2ij)) %>%
    ungroup()
}

calculate_df2i.prs <- function(mutants) {
  calculate_df2ij.prs(mutants) %>%
    group_by(i, mutation) %>%
    summarise(df2i = mean(df2ij)) %>%
    ungroup()
}

calculate_de2i.prs <- function(mutants) {
  calculate_de2ij.prs(mutants) %>%
    group_by(i, mutation) %>%
    summarise(de2i = mean(de2ij)) %>%
    ungroup()
}

calculate_dvsi.prs <- function(mutants) {
  calculate_dvsij.prs(mutants) %>%
    group_by(i, mutation) %>%
    summarise(dvsi = mean(dvsij)) %>%
    ungroup()
}

calculate_dvmi.prs <- function(mutants) {
  calculate_dvmij.prs(mutants) %>%
    group_by(i, mutation) %>%
    summarise(dvmi = mean(dvmij)) %>%
    ungroup()
}




# Mode-site response matrices ---------------------------------------------



#' Calculate structural mutational response, mode analysis
#'
calculate_dfnj.prs <- function(mutants) {
  # structural differences, mode analysis
  result <- mutants %>%
    mutate(n = map(wt, get_mode),
           dr2nj = map2(wt, mut, calculate_dr2n),
           de2nj = map2(wt, mut, calculate_de2n),
           df2nj = map2(wt, mut, calculate_df2n))
  result <- result %>%
    select(-wt, -mut) %>%
    unnest(c(n, dr2nj, de2nj, df2nj)) %>%
    select(n, j, mutation, dr2nj, df2nj, de2nj)
  result
}





# pair comparison ---------------------------------------------------------

calculate_dvsi.noindel <- function(wt, mut) {
  gwt <- get_graph(wt)
  gmut <- get_graph(mut)

  stopifnot(all(gmut$edge == gwt$edge)) # for "lfenm": this works if the network didn't change its topology

  gmut$vsij = 1/2 * gmut$kij * (gwt$dij - gmut$lij)^2
  gwt$vsij = 1/2 * gwt$kij * (gwt$dij - gwt$lij)^2
  dvsij = gmut$vsij - gwt$vsij

  dvsij_non_zero <- !near(dvsij, 0)

  dvsij <- dvsij[dvsij_non_zero]
  i <- gwt$i[dvsij_non_zero]
  j <- gwt$j[dvsij_non_zero]
  sites_non_zero <- unique(c(i,j))

  dvsi <- rep(0, get_nsites(wt))

  for (e in seq_along(dvsij))  {
    dvsi[i[e]] = dvsi[i[e]] + dvsij[e]
    dvsi[j[e]] = dvsi[j[e]] + dvsij[e]
  }

  dvsi
}









